repos:
  - repo: https://github.com/myint/autoflake
    rev: 'v1.4'
    hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--ignore-init-module-imports']
      name: autoflake
      entry: autoflake
      language: python
      'types': [python]
      require_serial: true
      exclude: ^(html|results)

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-eradicate==1.3.0"]
        exclude: ^(html|results)

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: ^(html|results)

  - repo: https://github.com/patrick91/pre-commit-alex
    rev: aa5da9e54b92ab7284feddeaf52edf14b1690de3
    hooks:
      - id: alex
        exclude: ^(html|results)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(html|results)
      - id: check-merge-conflict
        exclude: ^(html|results)
      - id: end-of-file-fixer
        exclude: ^(html|results)
      - id: check-toml
        exclude: ^(html|results)

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        exclude: ^(html|results)
