repos:
  - repo: https://github.com/patrick91/pre-commit-alex
    rev: aa5da9e54b92ab7284feddeaf52edf14b1690de3
    hooks:
      - id: alex
        exclude: ^(html|results)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(html|results)
      - id: check-merge-conflict
        exclude: ^(html|results)
      - id: end-of-file-fixer
        exclude: ^(html|results)
      - id: check-toml
        exclude: ^(html|results)

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        exclude: ^(html|results)

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.280
    hooks:
      - id: ruff
        exclude: ^tests/codegen/snapshots/python/
