name: "ASV Bot"

on:
  push:
    branches:
      - main
  schedule:
    - cron: "53 17 * * *"
  workflow_dispatch:
    inputs:
      number:
        description: 'Number of commits to benchmark'
        required: false

jobs:
  benchmark:
    name: "Run benchmarks"
    runs-on: self-hosted

    concurrency:
      group: ${{ github.actor }}-asv
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run benchmarks
        run: |
          ~/.local/bin/rtx activate bash
          ~/.local/bin/asv run HEAD~10..HEAD
        if: "${{ github.event.inputs.number == '' }}"

      - name: Run benchmarks
        run: |
          ~/.local/bin/rtx activate bash
          ~/.local/bin/asv run HEAD~${{ github.event.inputs.number }}..HEAD
        if: "${{ github.event.inputs.number != '' }}"

      - name: Publish benchmarks
        run: |
          ~/.local/bin/asv publish

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_options: '--no-verify --no-gpg-sign'
