name: "ASV Bot"

on:
  push:
    branches:
      - main
  schedule:
    - cron: "53 17 * * *"

jobs:
  benchmark:
    name: "Run benchmarks"
    runs-on: self-hosted

    concurrency:
      group: ${{ github.actor }}-asv
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run benchmarks
        continue-on-error: true
        run: |
          ~/.local/bin/asv run HEAD~10..HEAD

      - name: Publish benchmarks
        run: |
          ~/.local/bin/asv publish

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_options: '--no-verify --no-gpg-sign'
